### ISSUE TITLE
Export Drill Layer?

### ISSUE THREAD

**Issue by ghost** [easyw/kicad-action-tools#1]
Would it be possible to export the drill layer?  PCBNew can already plot a drill map file.  That's fine, except that the actual drill holes are replaced with symbols for easy identification.  (I just spent a couple of hours replacing those symbols with circles in a drawing so that I could verify a 3D model.)  Would it be possible to generate the drawing with the actual holes automatically, (with an option to include the contents of the edge cuts layer)?

**Comment by easyw** [comment]
@Khalinda
Why not usinv kicad StepUp? It has a feature to import the kicad footprint in freecad to check exactly this ...
