### ISSUE TITLE
Move selected drawing issue

### ISSUE THREAD

**Issue by pendragon8991** [easyw/kicad-action-tools#26]
Hello, i try to move an edge cuts outline to an aux layer, like user drawing or User 1, but i receive this error: 
![Screenshot 2023-11-19 114659](https://github.com/easyw/kicad-action-tools/assets/68713074/82153236-ed40-418f-968e-5b9fea56686c)

Is there a way to solve it?

**Comment by kscheff** [comment]
Looking the python console it looks like that the names could be reached by` pcbnew.BOARD.GetStandardLayerName()`.
I get the same message with KiCad 7.0.10 installed, you need to change the line 157 to:
`                LayerStdName = pcbnew.BOARD.GetStandardLayerName(LayerIndex)
`

**Comment by easyw** [comment]
this is solved in v1.0.7 release
