### ISSUE TITLE
在KICAD6.0 夜间版本中，拉取下来无法使用//In the night version of kicad6.0, it cannot be used when pulled down

### ISSUE THREAD

**Issue by AellenPan** [easyw/kicad-action-tools#5]
在Version: (6.0.0-rc1-220-ga224d8dd6c), release build版本中无法使用；

**Comment by easyw** [comment]
@AellenPan 
this should be solved with latest v1.0.4 package and kicad v6.0 since Dec 1

**Comment by easyw** [comment]
@AellenPan 
I'm going to close it... feel free to reopen in case of need
